# -*- coding: utf-8 -*-
"""kalkulator_suhu.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_IY2Bvh5XsYER2rYbTys1OkFZbCiTONP
"""

import streamlit as st

# Fungsi konversi suhu
def celsius_to_fahrenheit(celsius):
    return (celsius * 9/5) + 32

def celsius_to_kelvin(celsius):
    return celsius + 273.15

def fahrenheit_to_celsius(fahrenheit):
    return (fahrenheit - 32) * 5/9

def fahrenheit_to_kelvin(fahrenheit):
    return (fahrenheit - 32) * 5/9 + 273.15

def kelvin_to_celsius(kelvin):
    return kelvin - 273.15

def kelvin_to_fahrenheit(kelvin):
    return (kelvin - 273.15) * 9/5 + 32

# Judul aplikasi Streamlit
st.title("🌡️ Kalkulator Konverter Suhu")

# Pilihan konversi
conversion_options = {
    "Celsius ke Fahrenheit": "C_to_F",
    "Celsius ke Kelvin": "C_to_K",
    "Fahrenheit ke Celsius": "F_to_C",
    "Fahrenheit ke Kelvin": "F_to_K",
    "Kelvin ke Celsius": "K_to_C",
    "Kelvin ke Fahrenheit": "K_to_F",
}

# Dropdown untuk memilih jenis konversi
selected_conversion_text = st.selectbox(
    "Pilih jenis konversi:",
    list(conversion_options.keys())
)

selected_conversion_code = conversion_options[selected_conversion_text]

# Input suhu dari pengguna
temperature = st.number_input(f"Masukkan suhu dalam {selected_conversion_text.split(' ')[0]}:", value=0.0)

# Tombol untuk melakukan konversi
if st.button("Konversi"):
    result = None
    unit_result = ""
    unit_input = selected_conversion_text.split(' ')[0] # Ambil unit input (misal: Celsius, Fahrenheit, Kelvin)

    if selected_conversion_code == "C_to_F":
        result = celsius_to_fahrenheit(temperature)
        unit_result = "°F"
    elif selected_conversion_code == "C_to_K":
        result = celsius_to_kelvin(temperature)
        unit_result = "K"
    elif selected_conversion_code == "F_to_C":
        result = fahrenheit_to_celsius(temperature)
        unit_result = "°C"
    elif selected_conversion_code == "F_to_K":
        result = fahrenheit_to_kelvin(temperature)
        unit_result = "K"
    elif selected_conversion_code == "K_to_C":
        result = kelvin_to_celsius(temperature)
        unit_result = "°C"
    elif selected_conversion_code == "K_to_F":
        result = kelvin_to_fahrenheit(temperature)
        unit_result = "°F"

    if result is not None:
        st.success(f"Hasil konversi: {temperature:.2f} {unit_input} = **{result:.2f} {unit_result}**")

st.markdown("---")
